// pages/0019-test-vue/src/CounterCard.vue
<script setup lang="ts">
import { ref } from 'vue';

type Props = {
  title: string;
  initialCount: number;
  step?: number;
  actionLabel: string;
};

const props = withDefaults(defineProps<Props>(), {
  step: 1,
});

const count = ref(props.initialCount);

const increment = () => {
  count.value += props.step;
};
</script>

<template>
  <section class="border border-gray-300 bg-white p-4 rounded">
    <div class="mb-3">
      <h2 class="text-lg font-semibold">{{ props.title }}</h2>
    </div>
    <div class="flex items-center gap-3">
      <span>Count: {{ count }}</span>
      <button
        class="border border-gray-400 px-3 py-2 bg-gray-100"
        type="button"
        @click="increment"
      >
        {{ props.actionLabel }}
      </button>
    </div>
  </section>
</template>

// pages/0016-test-react/src/CounterCard.tsx
import { useState } from 'react';

type Props = {
  title: string;
  initialCount: number;
  step?: number;
  actionLabel: string;
};

export default function CounterCard({
  title,
  initialCount,
  step = 1,
  actionLabel,
}: Props) {
  const [count, setCount] = useState(initialCount);

  const handleIncrement = () => {
    setCount((value) => value + step);
  };

  return (
    <section className="border border-gray-300 bg-white p-4 rounded">
      <div className="mb-3">
        <h2 className="text-lg font-semibold">{title}</h2>
      </div>
      <div className="flex items-center gap-3">
        <span>Count: {count}</span>
        <button
          className="border border-gray-400 px-3 py-2 bg-gray-100"
          type="button"
          onClick={handleIncrement}
        >
          {actionLabel}
        </button>
      </div>
    </section>
  );
}
